# -*- coding: utf-8 -*-
"""Untitled28.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vbFTm5uOXUtbaAHlpidDQ_OJMLmr5USj
"""



pip install transformers soundfile datasets accelerate torch sentencepiece optimum torchaudio

from transformers import pipeline, AutoTokenizer
import torch


speech_to_text_pipeline = pipeline("automatic-speech-recognition", model="openai/whisper-small")


sentiment_pipeline = pipeline("sentiment-analysis", model="distilbert-base-uncased-finetuned-sst-2-english")


tts_tokenizer = AutoTokenizer.from_pretrained("suno/bark-small")
tts_pipeline = pipeline("text-to-speech", model="suno/bark-small")

print("Models loaded successfully!")

"""### Upload Audio File

Please upload the audio file you want to process. The file should be in a format supported by `openai/whisper-small` (e.g., WAV, MP3).
"""

from google.colab import files
import soundfile as sf
import os

uploaded = files.upload()

audio_path = None
for original_filename in uploaded.keys():
    new_filename = "uploaded_audio.wav"
    with open(new_filename, "wb") as f:
        f.write(uploaded[original_filename])
    audio_path = new_filename
    print(f"Uploaded file '{original_filename}' and saved as '{audio_path}'")

print(f"Using audio file at: {audio_path}")

from transformers import pipeline
import soundfile as sf
import librosa
import numpy as np

asr_pipeline = pipeline("automatic-speech-recognition", model="openai/whisper-small")

print("Speech-to-Text (Whisper) model loaded successfully.")

input_audio_filename = "/content/uploaded_audio.wav"

audio_data, sampling_rate = sf.read(input_audio_filename)

target_sampling_rate = 16000
if sampling_rate != target_sampling_rate:
    print(f"Resampling audio from {sampling_rate} Hz to {target_sampling_rate} Hz...")
    audio_data = librosa.resample(y=audio_data, orig_sr=sampling_rate, target_sr=target_sampling_rate)
    sampling_rate = target_sampling_rate
    print("Resampling complete.")

transcription_result = asr_pipeline({"array": audio_data, "sampling_rate": sampling_rate}, chunk_length_s=30)

print(f"\n--- Transcribed Text ---")
print(transcription_result["text"])

sentiment_result = sentiment_pipeline(transcription_result['text'])

print(f"\n--- Sentiment Analysis Result ---")
print(sentiment_result)

sentiment_model_name = "distilbert-base-uncased-finetuned-sst-2-english"
sentiment_tokenizer = AutoTokenizer.from_pretrained(sentiment_model_name)

text_to_analyze = transcription_result['text']
tokenized_text = sentiment_tokenizer.tokenize(text_to_analyze)

print(f"\n--- Tokenized Text ---")
print(tokenized_text)

sentiment_result = sentiment_pipeline(text_to_analyze)

print(f"\n--- Sentiment Analysis Result (after explicit tokenization display) ---")
print(sentiment_result)

sentiment_label = sentiment_result[0]['label']
sentiment_score = sentiment_result[0]['score']

if sentiment_label == 'NEGATIVE' and sentiment_score > 0.8:
    tts_text = "I understand you are very disappointed with the product and the unhelpful customer support. I apologize for the inconvenience you've experienced. We will look into this immediately."
elif sentiment_label == 'POSITIVE' and sentiment_score > 0.8:
    tts_text = "I'm glad to hear you are extremely happy with the service and the excellent results! We appreciate your feedback."
else:
    tts_text = "The sentiment of your message has been analyzed."

print(f"\n--- Generating TTS response: '{tts_text}' ---")

tts_output = tts_pipeline(tts_text)

output_audio_path = "sentiment_response.wav"
sf.write(output_audio_path, tts_output["audio"].squeeze(), tts_output["sampling_rate"])

